hawkular_tasks:
    - policy add-role-to-user edit system:serviceaccount:openshift-infra:metrics-deployer -n openshift-infra
    - policy add-cluster-role-to-user cluster-admin system:serviceaccount:openshift-infra:heapster

deployer_service_account:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: metrics-deployer
    secrets:
    - name: metrics-deployer

hawkular_tmp_conf: /tmp/hawkular_admin.kubeconfig

